add_executable(numerics_test numerics.cc)
target_link_libraries(numerics_test PRIVATE nn_options)
add_test(NAME numerics COMMAND numerics_test)
foreach(number IN ITEMS 1 2 4)
  add_executable(hw${number}_test perceptron.cc)
  target_link_libraries(hw${number}_test PRIVATE hw${number}_core)
  target_compile_definitions(hw${number}_test PRIVATE HOMEWORK=${number})
  add_test(NAME hw${number}-regression COMMAND hw${number}_test)
endforeach()
add_executable(optimization_test optimization.cc)
target_link_libraries(optimization_test PRIVATE hw3_core)
add_test(NAME optimization COMMAND optimization_test)
add_executable(genetic_test genetic.cc)
target_link_libraries(genetic_test PRIVATE hw4_core)
add_test(NAME genetic COMMAND genetic_test)
add_test(NAME hw1-demo COMMAND hw1)
add_test(NAME hw3-demo COMMAND hw3)
add_test(NAME hw2-help COMMAND hw2 --help)
add_test(NAME hw4-help COMMAND hw4 --help)
set_tests_properties(numerics hw1-regression hw2-regression hw4-regression
  optimization genetic hw1-demo hw3-demo hw2-help hw4-help PROPERTIES TIMEOUT 120)
