add_library(hw2_core STATIC perceptron.cc data_supplier.cc)
target_link_libraries(hw2_core PUBLIC nn_options)
target_include_directories(hw2_core PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}")
add_executable(hw2 main.cc)
target_link_libraries(hw2 PRIVATE hw2_core)
if(NN_ENABLE_PLOTS)
  target_compile_definitions(hw2 PRIVATE NN_ENABLE_PLOTS)
  target_link_libraries(hw2 PRIVATE Matplot++::matplot)
endif()
