add_library(hw1_core STATIC perceptron.cc data_supplier.cc)
target_link_libraries(hw1_core PUBLIC nn_options)
target_include_directories(hw1_core PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}")
add_executable(hw1 main.cc)
target_link_libraries(hw1 PRIVATE hw1_core)
if(NN_ENABLE_PLOTS)
  target_compile_definitions(hw1 PRIVATE NN_ENABLE_PLOTS)
  target_link_libraries(hw1 PRIVATE Matplot++::matplot)
endif()
