add_library(hw4_core STATIC perceptron.cc data_supplier.cc chromosome.cc genetic_algorithm.cc fitness_function.cc)
target_link_libraries(hw4_core PUBLIC nn_options)
target_include_directories(hw4_core PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}")
add_executable(hw4 main.cc)
target_link_libraries(hw4 PRIVATE hw4_core)
if(NN_ENABLE_PLOTS)
  target_compile_definitions(hw4 PRIVATE NN_ENABLE_PLOTS)
  target_link_libraries(hw4 PRIVATE Matplot++::matplot)
endif()
